# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='appartmens',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='house',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
