# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170315_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='appartmens',
            new_name='apartments',
        ),
    ]
